# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{multiauth}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David A. Cuadrado"]
  s.date = %q{2010-09-19}
  s.description = %q{multi authentication gem using devise & co}
  s.email = %q{krawek@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "app/views/multiauth/_box.html.erb",
     "lib/generators/multiauth/multiauth_generator.rb",
     "lib/generators/templates/README",
     "lib/generators/templates/devise_twitter.rb",
     "lib/generators/templates/images/arrow.gif",
     "lib/generators/templates/images/balloon.png",
     "lib/generators/templates/images/indicator.gif",
     "lib/generators/templates/images/openid-icons.png",
     "lib/generators/templates/multiauth.css",
     "lib/generators/templates/multiauth.js",
     "lib/multiauth.rb",
     "lib/multiauth/rails.rb",
     "lib/multiauth/views_helper.rb",
     "multiauth.gemspec",
     "spec/multiauth_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/dcu/multiauth}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{multi authentication gem using devise & co}
  s.test_files = [
    "spec/multiauth_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<rails>, ["= 3.0.0"])
      s.add_runtime_dependency(%q<mongomapper-devise>, ["= 1.2.0"])
      s.add_runtime_dependency(%q<devise_openid_authenticatable>, ["= 1.0.0.alpha7"])
      s.add_runtime_dependency(%q<devise-twitter>, ["= 0.1.1"])
      s.add_runtime_dependency(%q<devise_invitable>, ["= 0.3.2"])
      s.add_runtime_dependency(%q<oauth2>, ["= 0.0.13"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<rails>, ["= 3.0.0"])
      s.add_dependency(%q<mongomapper-devise>, ["= 1.2.0"])
      s.add_dependency(%q<devise_openid_authenticatable>, ["= 1.0.0.alpha7"])
      s.add_dependency(%q<devise-twitter>, ["= 0.1.1"])
      s.add_dependency(%q<devise_invitable>, ["= 0.3.2"])
      s.add_dependency(%q<oauth2>, ["= 0.0.13"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<rails>, ["= 3.0.0"])
    s.add_dependency(%q<mongomapper-devise>, ["= 1.2.0"])
    s.add_dependency(%q<devise_openid_authenticatable>, ["= 1.0.0.alpha7"])
    s.add_dependency(%q<devise-twitter>, ["= 0.1.1"])
    s.add_dependency(%q<devise_invitable>, ["= 0.3.2"])
    s.add_dependency(%q<oauth2>, ["= 0.0.13"])
  end
end

